### ISSUE TITLE
Auto Focus on Module delete

### ISSUE THREAD

**Issue by LanceJernigan** [LanceJernigan/Editor#4]
Previous module should become focused when a module is deleted.

**Comment by beardedtim** [comment]
As in the previously added or the last interacted?

**Comment by LanceJernigan** [comment]
The module above the one deleted.

So, if we have the following: 

`Module A
Module B
Module C`

Deleting Module C would cause Module B to become focused.

This is primarily geared toward text editing.  Once I delete one paragraph, I want the prior paragraph to come to focus so I can either pick up where I was or delete that paragraph, too.

**Comment by beardedtim** [comment]
Ah, okay. As long as the modules are held in the array, I would say make the index of the item removed -1 active. And have a check for 0 and make it 0 again.

**Comment by LanceJernigan** [comment]
Currently, each module has a `focus` property that dictates whether it becomes focused upon render or not.  This works for the initial load, but it doesn't seem to work upon updating a modules `focus` property.

You can see where this is supposed to happen here:
https://github.com/LanceJernigan/Editor/blob/master/src/components/Editor/index.js#L56

**Comment by LanceJernigan** [comment]
This should be fixed with #5.
